package me.jrkr.euler;

/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By listing the first six prime numbers: 2, 3, 5, 7, 11, and 13, we can see that the 6th prime is 13.
 * What is the 10 001st prime number?* Answered 12-03-16 - 4613732
 */
public class Problem7 extends BaseProblem {

    int primeCount = 2; // start the primeNumberCount (1, 2 are primes).
    public Problem7() {
        int start = 3;
        while (primeCount <= 10001) {
            if (isPrime(start)) {
                primeCount++;
                result = start;
            }
            start++;
        }

        System.out.println("10,001 Prime Number = " + result);
    }
    // method taken from mykong
    boolean isPrime(int n) {
        if (n % 2 == 0) return false;
        for (int i = 3; i * i <= n; i += 2) {
            if (n % i == 0) return false;
        }
        return true;
    }

    public static void main(String[] args) {
        new Problem7();
    }

}
